services:
  database:
    image: postgres
    container_name: database
    env_file:
      - auth.env
    networks:
      - database-network
    ports:
      - 5433:5432
    volumes:
      - ./database:/var/lib/postgresql/data

  pipeline:
    build: .
    env_file:
      - auth.env
    networks:
      - database-network

volumes:
  database:

networks:
  database-network: